"""
파이프라인에서 생성된 코드가 실제로 작동하는지 테스트
간단한 분류 파이프라인 시뮬레이션
"""

# ===== Generated by ML Pipeline Builder =====

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load Data from file (Iris dataset)
from sklearn.datasets import load_iris
iris = load_iris()
step_node1_data = pd.DataFrame(iris.data, columns=iris.feature_names)
step_node1_data['target'] = iris.target
print(f"Data loaded: {step_node1_data.shape}")
print("\nFirst 5 rows:")
print(step_node1_data.head())

# Train/Test Split
# Target column: 'target'
X_all = step_node1_data.drop('target', axis=1)
y_all = step_node1_data['target']
step_node2_X_train, step_node2_X_test, step_node2_y_train, step_node2_y_test = train_test_split(
    X_all, y_all, test_size=0.20, random_state=42
)
print(f"\nTrain size: {len(step_node2_X_train)}, Test size: {len(step_node2_X_test)}")
print(f"Target column: 'target'")

# Scale Data (StandardScaler)
step_node3_scaler = StandardScaler()
step_node3_X_train = step_node3_scaler.fit_transform(step_node2_X_train)
step_node3_X_test = step_node3_scaler.transform(step_node2_X_test)
print(f"\nData scaled with StandardScaler")
print(f"Train shape: {step_node3_X_train.shape}, Test shape: {step_node3_X_test.shape}")

# Train Classifier
step_node4_model = RandomForestClassifier(n_estimators=100, random_state=42)
step_node4_model.fit(step_node3_X_train, step_node2_y_train)
print("\nModel trained: RandomForest")
print(f"Training score: {step_node4_model.score(step_node3_X_train, step_node2_y_train):.4f}")

# Evaluate Model
step_node5_prediction = step_node4_model.predict(step_node3_X_test)
step_node5_metrics = {
    'accuracy': accuracy_score(step_node2_y_test, step_node5_prediction)
}
print(f"\n{'='*50}")
print(f"🎯 Final Results")
print(f"{'='*50}")
print(f"Accuracy: {step_node5_metrics['accuracy']:.4f}")
print("\nClassification Report:")
print(classification_report(step_node2_y_test, step_node5_prediction))
print("\nConfusion Matrix:")
print(confusion_matrix(step_node2_y_test, step_node5_prediction))

print(f"\n{'='*50}")
print("✅ 파이프라인이 성공적으로 실행되었습니다!")
print(f"{'='*50}")
